spring:
  application:
    name: courses-projects
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: root2019
server:
  error:
    include-stacktrace: on_trace_param
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/}
  instance:
    preferIpAddress: true